//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int ID { get; set; }
        public int DisciplinID { get; set; }
        public int TeacherID { get; set; }
        public int GroupID { get; set; }
    
        public virtual Disciplin Disciplin { get; set; }
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
